### ISSUE TITLE
 I cant use API level 24 for my Android Virtual Device in Android Studio 

### ISSUE THREAD

**Issue by Marietto2008** [3052/widevine#3]
Hello again.

I would like to create an Android virtual device on Ubuntu 24.04 with these characteristics :

```
abi = x86

api level = 24

target = Android 7.0 (Google APIs)
```

So I have created a model "Nexus 5 with API 24",but it didn't work because the error below :

```
2024-08-10 13:54:38,233 [ 398984]   WARN - Emulator: Nexus 5 API 24 - Failed to process .ini file /home/ziomario/.android/avd/../avd/Ne
xus_5_API_24.avd/quickbootChoice.ini for reading.
2024-08-10 13:54:38,320 [ 399071]   WARN - Emulator: Nexus 5 API 24 - FeatureControl is requesting a non existing feature.
2024-08-10 13:54:38,492 [ 399243]   WARN - Emulator: Nexus 5 API 24 - Emulator terminated with exit code 139
2024-08-10 13:54:39,046 [ 399797]   WARN - #com.android.sdklib.deviceprovisioner.DeviceAction - The emulator process for AVD Nexus_5_AP
I_24 has terminated.
com.android.tools.idea.avdmanager.EmulatorConnectionListener$EmulatorTerminatedException: The emulator process for AVD Nexus_5_API_24 h
as terminated.
at com.android.tools.idea.avdmanager.EmulatorConnectionListener$WaitForEmulatorTask.run(EmulatorConnectionListener.java:93)
at com.intellij.openapi.application.impl.RwLockHolder$executeOnPooledThread$1.run(RwLockHolder.kt:154)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
at java.base/java.lang.Thread.run(Thread.java:840)
2024-08-10 16:58:08,886 [11409637]   WARN - #c.i.u.i.p.ProjectIndexableFilesFilterHealthCheck - Following files are indexable but they
were NOT found in filter. Errors count: 1. Examples:
file id=456120 path=/home/ziomario/AndroidStudioProjects/MyApplication/.idea/appInsightsSettings.xml
```

According with this thread :

https://stackoverflow.com/questions/76595583/why-i-cant-use-api-level-from-29-to-34-avd-in-android-studio

the solution seems to be : 

> change graphics to software GLES 2.0 in emulated performance section

Unfortunately I can't change that value because it is greyed out. What should I do to unfreezes it ?

**Comment by 3052** [comment]
contact me privately if you are interested in paid support. otherwise good luck
